version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=tlc
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  # etherpad:
  #   image: etherpad/etherpad:stable
  #   container_name: pad
  #   ports:
  #     - "9001:9001"
  #   volumes:
  #     - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    ports:
      - "2525:25"

  back:
    build: ./api/
    ports:
      - 8080:8080

  front:
    build: ./front/
    ports:
      - 80:8080
      - 443:8443
